### PR TITLE
Speedup parsing

### LINKED ISSUE #83: Loading of large trajectory files
Currently, I'm simulating a scenario with 5k agents and 1.5h simulation time in a large geometry. Thus, the combined trajectory files become quite large (several GB). Often it takes 30 minutes to load the geometry and when sliding in time jpsvis fails/exits. 
My workaround so far: combine a few trajectory files (e.g., for 5 minutes simulation time) generated by jpscore and load one after the other with jpsvis to get an overview of the simulation results. This is very time-consuming and makes recording difficult.

Maybe it would be possible to load the trajectory files in chunks (in groups of trajectory files as they are accessed when sliding between frames)?

### PR DESCRIPTION
**Pull request by Ozaq**
Fixes #83

### CODE REVIEW

File: benchmarks/parsing.cpp [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+#include "TrajectoryData.h"
+
+#include <benchmark/benchmark.h>
+
+static void BM_ParseTxtFormat(benchmark::State & state)
+{
+    // Perform setup here
+    for(auto _ : state) {
+        TrajectoryData data;
+        Parsing::ParseTxtFormat("/Users/kkratz/Downloads/results/bottleneck_traj.txt", &data);
```
Comment (chraibi) [inline benchmarks/parsing.cpp:12]: hard-coded?

Comment (Ozaq) [reply benchmarks/parsing.cpp:12]: T.T yes, will clean it up
